services:
  machine:
    container_name: sc-machine
    image: ostis/sc-machine:latest
    build:
      context: ./sc-machine
    volumes:
      - ./kb:/kb
      - kb-binary:/kb.bin
    networks:
      - sc-machine
    ports:
      - "8090:8090"
    healthcheck:
      test: "python3 /sc-machine/scripts/healthcheck.py"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 120s
    environment:
      # Use the commented env variable if you need to rebuild KB every startup.
      - "REBUILD_KB=${REBUILD_KB:-1}"
      - "KB_PATH=${KB_PATH:-/kb/repo.path}"
      - "BINARY_PATH=/sc-machine/bin"
      - "CONFIG_PATH=/sc-machine/sc-machine.ini"
    command:
      - "serve"

  web:
    container_name: sc-web
    image: ostis/sc-web:latest
    build:
      context: ./sc-web
    restart: unless-stopped
    ports:
      - "80:8000"
    networks:
      - sc-machine
    command:
      - "--server-host=machine"
      - "--public-url=ws://localhost:8090/ws_json"
    depends_on:
      machine:
        condition: service_healthy  

volumes:
  kb-binary: {}

networks:
  sc-machine: {}
